/**
 * Bu metinlerdeki sorular her zaman **serbest metin** (klavye) kalmalı; şık listesi silinir.
 * Seed sonunda çalışır; daha önce çoktan seçmeli yapılmış satırları da metne döndürür.
 */
export type OpenTextPrompt = { phase: 'profile' | 'game'; prompt: string };

export const OPEN_TEXT_PROMPTS: OpenTextPrompt[] = [
  { phase: 'profile', prompt: 'En sevdiğin renk?' },
  { phase: 'game', prompt: 'Partnerinin en sevdiği renk?' },
  { phase: 'profile', prompt: 'En sevdiğin yemek?' },
  { phase: 'game', prompt: 'Partnerinin en sevdiği yemek?' },
  { phase: 'profile', prompt: 'Dinlemekten en çok keyif aldığın müzik türü hangisi?' },
  { phase: 'game', prompt: 'Partnerinin en çok dinlediği müzik türü nedir?' },
  { phase: 'profile', prompt: 'Birlikte geçireceğin ideal Pazar günü nasıl olurdu?' },
  { phase: 'game', prompt: 'Partnerinin ideal Pazar günü planı nedir?' },
  { phase: 'profile', prompt: 'En sevdiğin film türü?' },
  { phase: 'game', prompt: 'Arkadaşının en sevdiği film türü nedir?' },
  {
    phase: 'profile',
    prompt: 'Bir partide ilk 10 dakikada genelde ne yaparsın? (tanış, dans et, kenarda izle…)',
  },
  { phase: 'game', prompt: 'Rakibinin partide ilk 10 dakikada yaptığı şey nedir?' },
  { phase: 'profile', prompt: 'En sevdiğin masa / grup oyunu hangisi?' },
  { phase: 'game', prompt: 'Rakibinin en sevdiği grup oyunu nedir?' },
  {
    phase: 'profile',
    prompt: 'Takımda genelde hangi rolde parlıyorsun? (fikir, detay, sunum, koordinasyon)',
  },
  { phase: 'game', prompt: 'Rakibinin takımdaki güçlü rolü nedir?' },
  { phase: 'profile', prompt: 'Karaoke yapsan ilk söyleyeceğin şarkı türü veya örnek?' },
  { phase: 'game', prompt: 'Rakibinin karaoke seçimi ne olurdu?' },
  { phase: 'profile', prompt: 'Bir günlüğüne ünlü biriyle takas sansın; kim olurdu?' },
  { phase: 'game', prompt: 'Rakibinin bir günlük takas seçeceği ünlü kim olurdu?' },
  { phase: 'profile', prompt: 'Stres olduğunda sakinleşmek için ne yaparsın?' },
  { phase: 'game', prompt: 'Partnerinin stres anında yaptığı şey nedir?' },
  { phase: 'profile', prompt: 'İlişkide seni en çok mutlu eden küçük jest nedir?' },
  { phase: 'game', prompt: 'Partnerine göre seni en çok mutlu eden küçük jest nedir?' },
  { phase: 'profile', prompt: 'Boş zamanında en çok ne yaparsın?' },
  { phase: 'game', prompt: 'Arkadaşının boş zamanında yaptığı şey nedir?' },
  { phase: 'profile', prompt: 'Grup sohbetinde kendini hangi rolde görürsün? (ör. şakacı, dinleyici, organizatör)' },
  { phase: 'game', prompt: 'Arkadaşının grupteki rolü nedir?' },
  { phase: 'profile', prompt: 'Rastgele bir yetenek kazansan hangisini seçerdin?' },
  { phase: 'game', prompt: 'Arkadaşının seçeceği yetenek nedir?' },
  { phase: 'profile', prompt: 'Seni en çok güldüren küçük şey nedir?' },
  { phase: 'game', prompt: 'Arkadaşını en çok güldüren şey nedir?' },
  { phase: 'profile', prompt: 'Tek kelimeyle kendini nasıl tanımlarsın?' },
  { phase: 'game', prompt: 'Arkadaşının kendini tanımlayacağı tek kelime ne olurdu?' },
  { phase: 'profile', prompt: 'Toplantı öncesi hazırlanmayı sever misin? Nasıl yaparsın?' },
  { phase: 'game', prompt: 'Rakibinin toplantı öncesi hazırlık alışkanlığı nedir?' },
  { phase: 'profile', prompt: 'İş gününde enerjini en çok ne yükseltir?' },
  { phase: 'game', prompt: 'Rakibinin iş gününde enerjisini ne yükseltir?' },
  { phase: 'profile', prompt: 'Stresli deadline\u2019da ilk tepkin ne olur?' },
  { phase: 'game', prompt: 'Rakibinin deadline stresindeki ilk tepkisi nedir?' },
  // Eğlence & Parti — ek serbest metin (çoktan seçmeliler listede yok)
  { phase: 'profile', prompt: 'Partide en çok hangi içecek seni temsil eder?' },
  { phase: 'game', prompt: 'Rakibinin partideki imza içeceği ne olurdu?' },
  { phase: 'profile', prompt: 'Bir ice breaker sorun olsa ilk ne sorardın?' },
  { phase: 'game', prompt: 'Rakibinin tanışmayı açacağı soru ne olurdu?' },
  { phase: 'profile', prompt: 'En unutulmaz parti anını tek cümleyle anlatsan?' },
  { phase: 'game', prompt: 'Rakibinin anlatacağı unutulmaz parti anı ne olurdu?' },
  { phase: 'profile', prompt: 'Misafir olarak partiye geç kalınca içinden ilk geçen cümle ne?' },
  { phase: 'game', prompt: 'Rakibinin geç kalınca içinden geçen tipik cümle ne?' },
  { phase: 'profile', prompt: 'Partide en çok hangi yemeği ararsın?' },
  { phase: 'game', prompt: 'Rakibinin partide en çok aradığı atıştırmalık ne?' },
  { phase: 'profile', prompt: 'After partisi dediğinde aklına gelen ilk şey ne?' },
  { phase: 'game', prompt: 'Rakibinin “after” dediğinde çağrıştırdığı şey ne?' },
  { phase: 'profile', prompt: 'En sevdiğin parti teması veya dekor fikrin ne? (kısaca)' },
  { phase: 'game', prompt: 'Rakibinin seçeceği parti teması ne olurdu?' },
  { phase: 'profile', prompt: 'Yılbaşı gecesi için tek kelimeyle modun ne?' },
  { phase: 'game', prompt: 'Rakibinin yılbaşı modunu tek kelimeyle nasıl tarif edersin?' },
  { phase: 'profile', prompt: 'Piknik veya bahçe partisinde vazgeçilmezin ne?' },
  { phase: 'game', prompt: 'Rakibinin açık hava partisinde vazgeçilmezi ne?' },
  { phase: 'profile', prompt: 'Kahkaha atmadan edemediğin parti oyunu veya aktivite hangisi?' },
  { phase: 'game', prompt: 'Rakibini en çok güldüren parti aktivitesi ne?' },
  { phase: 'profile', prompt: 'Tek başına evde “parti modu” açsan ilk ne yaparsın?' },
  { phase: 'game', prompt: 'Rakibinin evde solo parti modunda yaptığı şey ne?' },
  { phase: 'profile', prompt: 'Partide en çok hangi hatayı yaparsın? (samimi)' },
  { phase: 'game', prompt: 'Rakibinin partide en çok yaptığı “klasik hata” ne?' },
  // İş arkadaşı — ek serbest metin
  { phase: 'profile', prompt: 'İş yerinde seni en çok rahatlatan küçük şey ne?' },
  { phase: 'game', prompt: 'Rakibini işte en çok rahatlatan küçük şey ne?' },
  { phase: 'profile', prompt: 'Patron veya yöneticiyle tek başına asansörde kalsan ilk konun ne olur?' },
  { phase: 'game', prompt: 'Rakibinin asansör sohbetinde açacağı konu ne?' },
  { phase: 'profile', prompt: 'İşyerinde duyduğun en absürt rivayı kısaca anlatsan?' },
  { phase: 'game', prompt: 'Rakibinin anlatacağı ofis rivayı ne tür olurdu?' },
  { phase: 'profile', prompt: 'Ofiste en çok hangi ses seni çıldırtır?' },
  { phase: 'game', prompt: 'Rakibini ofiste en çok rahatsız eden ses ne?' },
  {
    phase: 'profile',
    prompt: '“Bugün evden çalışıyorum” dediğinde gerçekten nerede olmak isterdin?',
  },
  { phase: 'game', prompt: 'Rakibinin ideal home office ortamı ne?' },
  { phase: 'profile', prompt: 'Kariyerinde seni en çok gururlandıran küçük an ne?' },
  { phase: 'game', prompt: 'Rakibinin gururla anlatacağı küçük iş anı ne?' },
  { phase: 'profile', prompt: 'İşe yeni biri başlayınca ona ilk tavsiyen ne olurdu?' },
  { phase: 'game', prompt: 'Rakibinin yeni başlayana ilk tavsiyesi ne olurdu?' },
  { phase: 'profile', prompt: 'Networking etkinliğinde ilk 10 dakikada ne yaparsın?' },
  { phase: 'game', prompt: 'Rakibinin networking açılışı ne?' },
  { phase: 'profile', prompt: 'Tek kelimeyle iş yerindeki “görünmez süper gücün” ne?' },
  { phase: 'game', prompt: 'Rakibinin iş yerindeki gizli süper gücü ne?' },
  { phase: 'profile', prompt: 'Yöneticine kötü haber verirken stratejin ne?' },
  { phase: 'game', prompt: 'Rakibinin kötü haber verme stratejisi ne?' },
  // Aile — yalnızca serbest metin (klavye) soruları; çoktan seçmeliler listede yok
  { phase: 'profile', prompt: 'Çocukken en çok hangi aile aktivitesini severdin?' },
  { phase: 'game', prompt: 'Diğer oyuncunun çocukken en sevdiği aile aktivitesi neydi?' },
  { phase: 'profile', prompt: 'En sevdiğin geleneksel yemek veya tatlı hangisi?' },
  { phase: 'game', prompt: 'Diğer oyuncunun en sevdiği geleneksel lezzet nedir?' },
  { phase: 'profile', prompt: 'Bayramlarda seni en çok ne heyecanlandırır?' },
  { phase: 'game', prompt: 'Diğer oyuncuyu bayramda en çok ne heyecanlandırır?' },
  { phase: 'profile', prompt: 'Aile sohbetlerinde en çok hangi konuya girersin?' },
  { phase: 'game', prompt: 'Diğer oyuncunun aile sohbetlerinde en çok girdiği konu nedir?' },
  { phase: 'profile', prompt: 'Büyüklerden öğrendiğin en değerli tavsiye (kısaca)?' },
  { phase: 'game', prompt: 'Diğer oyuncunun söyleyeceği tavsiye hangisi olurdu?' },
  { phase: 'profile', prompt: 'Ailede en haz etmediğin akraba / ziyaret tarafı kimler?' },
  { phase: 'game', prompt: 'Diğer oyuncunun en haz etmediği akraba veya ziyaret tarafı kim?' },
  { phase: 'profile', prompt: 'Aile içinde en çok kimi gizlice daha çok sevdiğini düşünürsün? (ismi yaz)' },
  { phase: 'game', prompt: 'Diğer oyuncunun gizlice daha çok sevdiği aile üyesi kimdir?' },
  { phase: 'profile', prompt: 'Ailede en az anlaşabildiğin kişi kim?' },
  { phase: 'game', prompt: 'Diğer oyuncunun ailede en az anlaşabildiği kişi kim?' },
  { phase: 'profile', prompt: 'Küçükken en çok sevdiğin oyuncak neydi?' },
  { phase: 'game', prompt: 'Diğer oyuncunun küçükken en çok sevdiği oyuncak neydi?' },
  { phase: 'profile', prompt: 'Küçükken büyüyünce ne olmak isterdin?' },
  { phase: 'game', prompt: 'Diğer oyuncunun küçükken ne olmak istediği neydi?' },
  { phase: 'profile', prompt: 'Çocukken en çok hangi abur cuburu yerdin?' },
  { phase: 'game', prompt: 'Diğer oyuncunun çocukken en çok yediği abur cubur neydi?' },
  { phase: 'profile', prompt: 'Küçükken ailenle en çok hangi mekâna giderdin? (park, yazlık, AVM…)' },
  { phase: 'game', prompt: 'Diğer oyuncunun küçükken ailenle favori gittiği mekân neresiydi?' },
  { phase: 'profile', prompt: 'Hangi akrabanın yanında daha temkinli konuşursun?' },
  { phase: 'game', prompt: 'Diğer oyuncunun yanında daha temkinli olduğu akraba kim?' },
  { phase: 'profile', prompt: 'En çok hangi aile büyüğüne benzetilirsin?' },
  { phase: 'game', prompt: 'Diğer oyuncuyu en çok hangi büyüğe benzetirsiniz?' },
  { phase: 'profile', prompt: 'Eski günlerden en çok hangi konuyu anlatırsın?' },
  { phase: 'game', prompt: 'Diğer oyuncunun en çok hangi eski gün konusunu anlattığı nedir?' },
  { phase: 'profile', prompt: 'Anneanne veya babaanne en çok hangi torunu şımartır? (sence)' },
  { phase: 'game', prompt: 'Diğer oyuncunun en çok şımartılan torun dediği kim?' },
  { phase: 'profile', prompt: 'Sinirlenince en çok tekrar ettiğin cümle veya söz ne?' },
  { phase: 'game', prompt: 'Diğer oyuncunun sinirlenince en çok söylediği şey nedir?' },
  { phase: 'profile', prompt: 'En çok kimi eleştirirsin ama onsuz da yapamazsın?' },
  { phase: 'game', prompt: 'Diğer oyuncunun eleştirir ama vazgeçemez dediği kim?' },
  { phase: 'profile', prompt: 'Ailede en iyi yemek yapan kişi sence kim?' },
  { phase: 'game', prompt: 'Diğer oyuncunun en iyi aşçı dediği kim?' },
  { phase: 'profile', prompt: 'Evde hangi yemeğin kokusu seni en çok çocukluğuna götürür?' },
  { phase: 'game', prompt: 'Diğer oyuncuyu çocukluğuna götüren yemek kokusu hangisi?' },
  { phase: 'profile', prompt: 'Aile içinde sana takılan en tatlı lakap neydi?' },
  { phase: 'game', prompt: 'Diğer oyuncunun aile içindeki lakabı neydi?' },
  { phase: 'profile', prompt: 'Ailecek izlenen ilk diziyi / programı hatırlıyor musun? (tür veya isim)' },
  { phase: 'game', prompt: 'Diğer oyuncunun hep birlikte izlerdik dediği şey neydi?' },
  { phase: 'profile', prompt: 'Ailenle en çok hangi şarkıyı veya türküyü mırıldanırdınız?' },
  { phase: 'game', prompt: 'Diğer oyuncunun ailece mırıldandığı şarkı veya türkü neydi?' },
  { phase: 'profile', prompt: 'Çocukken yazın en çok nerede büyüdün? (mahalle, köy, site…)' },
  { phase: 'game', prompt: 'Diğer oyuncunun çocukluk yazlarını en çok nerede geçirdiği nedir?' },
  { phase: 'profile', prompt: 'Evde en çok hangi koku anne eli değmiş der?' },
  { phase: 'game', prompt: 'Diğer oyuncunun anne eli dediği koku veya lezzet hangisi?' },
  { phase: 'profile', prompt: 'Aile içinde gizli şampiyon olduğun şey ne? (kimse bilmez sandığın)' },
  { phase: 'game', prompt: 'Diğer oyuncunun aile içinde gizli güçlü olduğu alan ne?' },
];
